### PR TITLE
IBX-3465: Copied vhost templates from docker repo

### PR DESCRIPTION
**Pull request by glye**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-3465](https://issues.ibexa.co/browse/IBX-3465)
| **Type**                                   | improvement
| **Target Ibexa version** | `v4.5`
| **BC breaks**                          | no

We should maintain vhost templates. The docker repo is no longer maintained. As discussed in https://github.com/ezsystems/developer-documentation/pull/1704 we can copy them from the docker repo to here, as this PR does.

Future improvement: Make a command for generating vhosts, similar to the bash script we had in eZ Platform: https://github.com/ezsystems/ezplatform/blob/master/bin/vhost.sh

#### Checklist:
- [x] Provided PR description.
- [x] ~Tested the solution manually.~
- [x] ~Provided automated test coverage.~
- [x] ~Checked that target branch is set correctly (`main` for features, the oldest supported for bugs).~
- [x] ~Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).~
- [x] Asked for a review (ping `@ibexa/engineering`).

### CODE REVIEW

**Comment by glye** [comment]
Test failures are irrelevant (phpstan plugin blocked by config)

**Review by adamwojs — APPROVED** [review]

**Comment by adamwojs** [comment]
Small remark: can we change `ez_` prefix to `ibexa_` in file names  ?

**Comment by Nattfarinn** [comment]
@glye Can you rebrand them from `ez` to `ibexa`?

**Comment by glye** [comment]
Rebranded from ez to ibexa. Rebased on updated main branch, because whoops, 10 weeks have passed.

**Review by Nattfarinn — APPROVED** [review]

**Pull request merged**
