### PR TITLE
Merge branch '1.0' into 4.6

### PR DESCRIPTION
**Pull request by glye**
Merge up of https://github.com/ibexa/post-install-ghsa-4h8f-c635-25p7/pull/1

### CODE REVIEW

**Review by ViniTou — APPROVED** [review]
but please avoid branch names like `1.0` for doing merges.

**Comment by glye** [comment]
@ViniTou What's preferred? "Merge remote-tracking branch 'origin/1.0' into 4.6"?

**Comment by ViniTou** [comment]
@glye 
Scratch it, I didnt realise that we have `1.0` as stable branch in post-install.

**Comment by glye** [comment]
Not sure what happened here. This PR looks OK to me, but the 1.0 branch looks borked indeed.

**Comment by ViniTou** [comment]
@glye 
Didnt you maybe - merge 4.6 to 1.0, then during conflict resolution modified everything to remove changes from 4.6 and now try do merge it back again to 4.6? Anyway, this needs to be redone.

**Comment by glye** [comment]
That's what I get from being stressed and following github instructions to the letter. Discussing fixes with Dawid & Marek

**Comment by glye** [comment]
New, separate PR for 4.6: https://github.com/ibexa/post-install/pull/86

**Pull request closed without merging**
