### PR TITLE
IBX-772: Fixes bad link to composer auth var setup

### PR DESCRIPTION
**Pull request by crevillo**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-772](https://issues.ibexa.co/browse/IBX-772)
| **Type**                                   | bug
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | no

There is a deadline in the comment of platform.app.yaml generated for ibexa commerce. I checked the others and it seems there are fine. 

ping @ibexa/engineering 

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ibexa/engineering`).

### CODE REVIEW

**Review by adamwojs — APPROVED** [review]

**Comment by lserwatka** [comment]
Is 1.0 brach affected as well?

**Comment by crevillo** [comment]
sorry, I didn't check that. Yes, looks affected. Should I change the pull request to merge into that branch?

**Comment by lserwatka** [comment]
Yes, please. Just change target branch to 1.0.

**Comment by crevillo** [comment]
Target branch changed. Still we may need another commit to master to fix the 4.x .platform.app.yaml which is not present in the 1.0 branch.

**Review by damianz5 — APPROVED** [review]

**Review by Steveb-p — APPROVED** [review]

**Review by webhdx — APPROVED** [review]

**Pull request merged**
